var cliente1 = "Jorge";
var cliente2 = "Camila";
var cliente3 = "Sara";
var comida1 = "abacate";
var comida2 = "berinjela";
var comida3 = "uva";
var comida4 = "arroz";
var comida5 = "maçã";
var nome1 = "Maria";
var nome2 = "Cristina";
var sobrenome1 = "Silva";
var sobrenome2 = "Castro";
console.log(nome1, sobrenome1);
console.log(nome2, sobrenome2);
var isEntrar = true;
var isLogar = false;
var isOnline = true;
var isAtivo = false;
var isVerdadeiro = true;
var isClicar = true;
var n1 = Math.floor(Math.random() * 1 + 1);
var n2 = Math.floor(Math.random() * 2 + 1);
var n3 = Math.floor(Math.random() * 3 + 1);
var n4 = Math.floor(Math.random() * 4 + 1);
var n5 = Math.floor(Math.random() * 5 + 1);
var n6 = Math.floor(Math.random() * 6 + 1);
var n7 = Math.floor(Math.random() * 7 + 1);
var n8 = Math.floor(Math.random() * 8 + 1);
var pi = 3.14;
var e = 2.71;
var r2 = 1.41;
var r3 = 1.73;
var gn = 1.61;
var diferenca = n1 - n2;
var divisao = n3 / n1;
var Multiplique = n5 * n2;
var resto = n4 % n6;
function Converter() {
    var valor = document.getElementById("valor").value;
    alert(parseFloat(valor) * 0.05 + " é 5% do valor informado!");
}
var r9 = Math.sqrt(9);
var ra2 = Math.sqrt(2);
console.log(r9);
console.log(ra2);
var p5 = Math.pow(7, 2);
console.log(p5);
var num1 = 7;
var num2 = 8.5;
var num3 = 22;
var num4 = 37.8;
var somaDosTotais = (num1 + num2 + num3 + num4);
console.log(somaDosTotais);
